DFRobotMaqueenPlus.I2CInit()
basic.forever(function () {
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.GREEN)
    basic.pause(1000)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.OFF)
    basic.pause(500)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.YELLOW)
    basic.pause(1000)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.OFF)
    basic.pause(1000)
})
basic.forever(function () {
    DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CW, 30)
    basic.pause(1000)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(500)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(1000)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(1000)
})
basic.forever(function () {
    music.startMelody(music.builtInMelody(Melodies.Ringtone), MelodyOptions.Forever)
    basic.pause(1000)
    music.stopAllSounds()
    basic.pause(500)
    music.startMelody(music.builtInMelody(Melodies.JumpUp), MelodyOptions.Forever)
    basic.pause(1000)
    music.stopAllSounds()
    basic.pause(1000)
})
